### ISSUE TITLE
"exit-code" fail when testing Spotify connect 

### ISSUE THREAD

**Issue by MikkelLau** [RafaPolit/moode-spotify-connect-web#7]
Hi There 

Thanks for the great piece of code:-) 
I am having some trouble when I want to test if the Spotify connect is working. I get the following error:
"spotify-connect-web.service: Failed with result 'exit-code'."
I am using a I2S DAC using a PCM1794 from Twisted Pear Audio. I am using the "DDDAC1794 NOS" driver and newest Moode. 

I have set the HW to "CARD=sndrpirpidac,DEV=0" and that plays static left and right using the speaker-test. I have changed "mixer_device_index" to 0, 1 and 2 in the spotify-connect.sh script, but still the same error with exit-code.

Could you have any idea of what I am doing wrong please?

Thanks in advance.

Best regards Mikkel

![skaermbillede 2018-05-14 kl 11 31 03](https://user-images.githubusercontent.com/35535841/39989498-6882583e-576a-11e8-946f-42518f1965bf.png)

**Comment by RafaPolit** [comment]
Sorry for the late reply.  Answered in the moode forum:
http://moodeaudio.org/forum/showthread.php?tid=14&pid=1432#pid1432

Hopefully with me and other's input we can figure this out.

**Comment by MikkelLau** [comment]
Thanks Rafael. I will comment on MoodeAudio fourm :-)
