### ISSUE TITLE
Device not listed in spotify.

### ISSUE THREAD

**Issue by bfaught** [RafaPolit/moode-spotify-connect-web#8]
I got through the entire process. I am using a USB DAC and the pink noise is properly routed through to the correct speakers. When I reboot I cannot get the moode device to show up in spotify. I have tried both device index 1 and 0, hoping to get some assistance.

**Comment by RafaPolit** [comment]
Sometimes changing the mixer from 0 to 1 can help.

Recently, the best troubleshooter has been running the script without the service to be able to read the actual error.

So, please
```
$ sudo systemctl disable spotify-connect-web.service
$ sudo systemctl stop spotify-connect-web.service
$ cd /home/pi/spotify
$ ./spotify-connect.sh
```

What is the output of this? This should provide the actual error if something is wrong.

Best regards,
Rafa.

**Comment by bfaught** [comment]
Hi Rafa,

Thanks for your help,
 
I get this,

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from gevent.wsgi import WSGIServer
ImportError: No module named wsgi

I am not very proficient with linux so this is a bit over my head, after looking online it seems the wsgi.py file maybe missing from the connect-web folder on my install? I'm sure its something simple I missed. 

Thanks again,
Ben

**Comment by RafaPolit** [comment]
This was reported over at the Moode forum by another member, please take a look at this:
http://moodeaudio.org/forum/showthread.php?tid=14&pid=1504#pid1504

It may appear that the procedure on new rasbian is missing some libraries. Hope this helps,
Best regards,
Rafa.

**Comment by RafaPolit** [comment]
The question raised by that post is actually resolved on a later post:
http://moodeaudio.org/forum/showthread.php?tid=14&pid=1507#pid1507

**Comment by bfaught** [comment]
That resolved the issue, everything is working. Thank you very much!
